language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python setup.py test
after_success: coveralls
deploy:
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: forecaster
    manifest: manifest.yml
