language: python
python:
- '3.5'
addons:
  postgresql: "9.4"
install:
- pip install -r requirements.txt
- pip install coveralls
services:
  - postgresql
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database flask_test;' -U postgres
  - python setup.py develop
  - python scripts/manage_db.py db upgrade
script:
- coverage run --source=flask_forecaster setup.py test
after_success: coveralls
deploy:
  - provider: cloudfoundry
    edge: true
    api: $CF_API
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: $CF_ORG
    space: $CF_SPACE
    manifest: manifest.yml

