"""empty message

Revision ID: 1ac7cf270bce
Revises: None
Create Date: 2016-03-11 17:03:06.829268

"""

# revision identifiers, used by Alembic.
revision = '1ac7cf270bce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_history',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_history')
    ### end Alembic commands ###
